import { Utility } from "utility.slint";
import { Theme } from "theme.slint";
export component AnimatedImage inherits Rectangle {
    in-out property <int> current_frame;
    in-out property <bool> animation;
    in-out property <int> total-frames;
    in-out property <string> gif-name;
    in-out property <int> fps;

    img := Image {
        height: 100%;
        image-fit: contain;
        source: @image-url("gifs/pickup/4.png");
    }

    width: img.width;

    Timer {
        interval: 1s / root.fps;
        running: animation;
        triggered => {
            img.source = Utility.load_gif_frame(root.gif-name, root.current_frame);
            current_frame = (current_frame + 1);
            current_frame = Math.mod(current_frame, total-frames);
        }
    }
}