import "./font/MinecraftRegular.otf";
export global Theme {
    out property <brush> background: @linear-gradient(0deg, #4a3856 0%, #4a3856 5%, #c7b7ce 88%, #c7b7ce 100%);
    out property <brush> background_start: #4a3856;
    out property <brush> background_end: #c7b7ce;
    out property <color> item_1: #9768a7;
    out property <color> item_2: rgba(151, 104, 167, 0.4);
    out property <int> name;

    out property <string> minecraft_font: "Minecraft";

    out property <image> icon: @image-url("./image/icon.png");
    out property <image> github: @image-url("./image/github_icon.png");
    out property <image> modrinth: @image-url("./image/modrinth_icon.png");
    out property <image> curseforge: @image-url("./image/curseforge_icon.png");
    out property <image> discord: @image-url("./image/discord_icon.png");
    out property <image> display: @image-url("./image/display.png");
    out property <image> crafting: @image-url("./image/crafting.jpg");
}