modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"

[[mods]]
modId = "bettershulkers"
version = "${version}"
displayName = "Better Shulkers"
authors = "noramibu, QPCrummer"
description = '''
A server-side mod that adds many features to shulkers.
'''
logoFile = "META-INF/icon.png"

[[dependencies.bettershulkers]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettershulkers]]
modId = "minecraft"
type = "required"
versionRange = "%mcVer%"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettershulkers]]
modId = "architectury"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bettershulkers.mixins.json"
